### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [OktaSecurityLabs/passprotect-js#6]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, your logo on this project not attractive and generic . Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by rdegges** [comment]
That'd be awesome! I'd love to see it <3 I ended up getting this one from 99designs and messing around with it, but any help would be greatly appreciated.

**Comment by mansya** [comment]
I have design icon for this project. what do you think ? do you like it ?
![passprotect-js](https://user-images.githubusercontent.com/33461607/41962316-e44d8138-7a1e-11e8-8716-5362802f08d9.png)

sorry for a long time.
