### ISSUE TITLE
False positives on CPlusPlus.com

### ISSUE THREAD

**Issue by Donaldpherman** [OktaSecurityLabs/passprotect-js#7]
Whenever I go to http://www.cplusplus.com I get a lot of warnings about my password but I'm not logged-in to the website or even trying to log-in.

**Comment by rdegges** [comment]
Hey there!

I just tested this out, but don't have the same behavior. One thing I did notice, however, is that they have a login box on each page. So if you have a password manager or something that might be inserting your credentials INTO the login box automatically, that would trigger passprotect to fire off an alert.

That's about all I can think of right now. Any chance you have another extension injecting credentials there?

-R

**Comment by Donaldpherman** [comment]
That probably what it is.  LastPass automatically put the password into the log-in screen.  I'll disable the auto-login for that website.  Thanks!

**Comment by rdegges** [comment]
Awesome, sounds good!
